version: '3'
services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - POSTGRES_DB=${POSTGRES_DB}
      - OWM_API_KEY=${OWM_API_KEY}
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: "postgres:13"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
